# syntax=docker/dockerfile:1
FROM python:3.8-slim-buster

RUN mkdir /mb

COPY api/ /mb
COPY pyproject.toml /mb

WORKDIR /mb

ENV PYTHONPATH=${PYTHONPATH}:${PWD}

RUN pip3 install poetry
RUN python -m pip install "pymongo[srv]"
RUN poetry config virtualenvs.create false
RUN poetry install --no-dev
