FROM node:12.18.3-alpine3.12

RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app/node_modules

WORKDIR /home/node/app

COPY package*.json ./

RUN npm install

COPY index.js ./
COPY routes.json ./
COPY db.json ./

USER node

EXPOSE 3000

CMD ["node", "index.js"]
