version: '3'

services:
  script:
    container_name: script
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/script

  fakeapi:
    container_name: fakeapi
    build:
      context: .
      dockerfile: Dockerfile.fakeapi

  mms_api:
    container_name: mms_api
    build:
      context: .
      dockerfile: Dockerfile.api
    command: "python api/run.py"
    volumes:
      - .:/mb
    ports:
      - "5000:5000"



networks:
  default:
    external: true
    name: nat
