from decouple import config

class Settings:
    # DEFINITION FILE DIRECTORIES
    PROJECT_FOLDER = config('PROJECT_FOLDER')
    DEFINITION_FILE = PROJECT_FOLDER + '/' + config('MB_PATH_JOB_DEFINITIONS')
    WORKDIRECTORY_TO_RESULTS = config('WORKDIRECTORY_TO_RESULTS')
    WORKDIRECTORY_TO_RETRY = config('WORKDIRECTORY_TO_RETRY')

    #DATABASE ENV
    MONGO_URI = config('MONGO_URI')

    # PROJECT ENV
    JOB_RETRIES = int(config('JOB_RETRIES'))
    RETRY_FILENAME = 'retries'
    UNPROCESSED_FILENAME = 'unprocessed_dates'

    IS_RETRY = False

    START_DATE = None
    END_DATE = None

    PAIRS_TO_RETRY = []
