from decouple import config

__all__ = [
    'DEFINITION_FILE',
]
# DEFINITION FILE DIRECTORIES
PROJECT_FOLDER = config('PROJECT_FOLDER') + "/"
DEFINITION_FILE = PROJECT_FOLDER + config('MB_PATH_JOB_DEFINITIONS')

